// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqxUmdp4Da9MkvlOhewzgLCzBPk2B_JM',
    appId: '1:225856265598:web:a8d7b2f7ef2dec5862a72f',
    messagingSenderId: '225856265598',
    projectId: 'campus-connect-nust',
    authDomain: 'campus-connect-nust.firebaseapp.com',
    storageBucket: 'campus-connect-nust.firebasestorage.app',
    measurementId: 'G-S1YEN2QVNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjd6CYgBfyZo8hZ2X9G2lyfBqpLfCiqc',
    appId: '1:225856265598:android:07e20fc325ad819f62a72f',
    messagingSenderId: '225856265598',
    projectId: 'campus-connect-nust',
    storageBucket: 'campus-connect-nust.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAt11MMhhDBEXyqB0C5PEACJJdAkbCcs',
    appId: '1:225856265598:ios:ea681bc992a8b64b62a72f',
    messagingSenderId: '225856265598',
    projectId: 'campus-connect-nust',
    storageBucket: 'campus-connect-nust.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpAt11MMhhDBEXyqB0C5PEACJJdAkbCcs',
    appId: '1:225856265598:ios:ea681bc992a8b64b62a72f',
    messagingSenderId: '225856265598',
    projectId: 'campus-connect-nust',
    storageBucket: 'campus-connect-nust.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJqxUmdp4Da9MkvlOhewzgLCzBPk2B_JM',
    appId: '1:225856265598:web:76e2f3954e2108b062a72f',
    messagingSenderId: '225856265598',
    projectId: 'campus-connect-nust',
    authDomain: 'campus-connect-nust.firebaseapp.com',
    storageBucket: 'campus-connect-nust.firebasestorage.app',
    measurementId: 'G-5VYFRQB4BW',
  );
}
